server:
  port: 10002
spring:
  application:
    name: config-ssm
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sys_permission?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.qf.j1902.pojo
  mapper-locations: classpath:/*.xml
myname: muxinke -23 xian
